on:
  push:
    branches:
      - master

name: Build and Publish Library
jobs:
  build:
    name: Deploy Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 14.21.3
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Install Dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Test Library
        run: npm run-script test
      - name: Build Library
        run: npm run-script build
      - name: Publish
        uses: Github-Actions-Community/merge-release@22d66d3f7750d57b2b8c05db6077205332527df8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
